let form = document.getElementById("regform");
let fullname = document.getElementById("fullname");
let email = document.getElementById("email");
let password = document.getElementById("password");
let dob = document.getElementById("dob");
let gender = document.querySelector('input[name="gender"]:checked');
let department = document.querySelector('input[name="department"]:checked');
let skills = document.querySelector('input[name="skills"]:checked');
let address = document.getElementById("address");
